# Generated by Django 5.2.7

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_at', models.DateTimeField()),
                ('event_type', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('session_id', models.CharField(max_length=255)),
                ('game_reference', models.CharField(max_length=255)),
                ('game_level', models.IntegerField()),
                ('game_mode', models.CharField(max_length=255)),
                ('game_color', models.CharField(max_length=255)),
                ('game_sequence', models.JSONField(default=list)),
                ('game_player_input', models.JSONField(default=list)),
            ],
        ),
    ]