# Generated by Django 5.2.7 on 2025-10-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='mac_address',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17),
        ),
    ]
