# Generated by Django 5.2.7 on 2025-10-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='event_category',
            field=models.CharField(default='general', max_length=255),
        ),
    ]
