# Generated by Django 5.2.7 on 2025-10-24 22:27

from django.db import migrations


def populate_event_category(apps, schema_editor):
    GameData = apps.get_model('sphere_game_data_api', 'GameData')
    for gamedata in GameData.objects.filter(event_category__isnull=True):
        gamedata.event_category = 'general'
        gamedata.save()


def reverse_populate_event_category(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0002_gamedata_event_category'),
    ]

    operations = [
        migrations.RunPython(populate_event_category, reverse_populate_event_category),
    ]
