# Generated by Django 5.2 on 2025-10-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0002_gamedata_mac_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedata',
            name='error_messages',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gamedata',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
