# Generated by Django 5.2.7 on 2025-10-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0003_gamedata_error_messages_gamedata_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
