# Generated by Django 5.2.7 on 2025-10-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0003_auto_20251025_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='event_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='event_category',
            field=models.CharField(db_index=True, default='general', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='event_type',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='game_level',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='game_mode',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='session_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='gamedata',
            index=models.Index(fields=['session_id', 'event_at'], name='gd_session_time_idx'),
        ),
        migrations.AddIndex(
            model_name='gamedata',
            index=models.Index(fields=['event_type', 'event_category'], name='gd_type_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='gamedata',
            index=models.Index(fields=['event_at', 'event_type'], name='gd_time_type_idx'),
        ),
        migrations.AddIndex(
            model_name='gamedata',
            index=models.Index(fields=['ip_address', 'event_at'], name='gd_ip_time_idx'),
        ),
    ]
