# Generated by Django 5.2.7 on 2025-10-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0004_alter_gamedata_game_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
