# Generated by Django 5.2.7 on 2025-10-24 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0005_gamedata_correct_game_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='is_correct_color',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
