# Generated by Django 5.2.7 on 2025-10-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0005_auto_20251025_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game_color',
            field=models.CharField(default='', max_length=255),
        ),
    ]
