# Generated by Django 5.2.7 on 2025-10-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0006_alter_gamedata_game_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedata',
            name='game_color',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='gamedata',
            name='game_reference',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
