# Generated by Django 5.2.7 on 2025-10-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0006_make_is_correct_color_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='is_correct_color',
        ),
    ]
