# Generated by Django 5.2.7 on 2025-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sphere_game_data_api', '0007_remove_is_correct_color_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedata',
            name='mac_address',
        ),
        migrations.AddField(
            model_name='gamedata',
            name='player_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
